### ISSUE TITLE
Only list categories with related entries

### ISSUE THREAD

**Issue by RyanRoberts** [helloswish/craft-faceted-navigation#2]
Hey, first up thanks for developing the plugin.

I'm sure I _should_ be able to figure this out but all the usual methods (basically using relatedTo) aren't working. I'd like to only list categories in the grouped lists if they have a related entry to avoid empty categories being listed.

Any thoughts?

**Comment by chadcrowell** [comment]
Hi Ryan how are you?

Ya that makes sense. I can see that use case. I don't have an answer for you right now... I happen to be in the middle of setting up a new laptop and don't have all my coding tools in place currently. It will be a few days until I can spend any real time looking into this for you to see if it can be done.

**Comment by RyanRoberts** [comment]
Good thanks. No problem at all, there's no rush as all the categories I have should be full at the moment but I can imagine when a site develops over time some may end up empty.

**Comment by chadcrowell** [comment]
OK, got this worked out. I based it off of [this article](https://straightupcraft.com/articles/how-do-i-only-display-a-list-of-categories-that-have-entries-and-hide-empty-categories).

At the top of your page, add something like this:
`{% set activeProductIds = craft.products.ids() %}` or
`{% set activeEntryIds = craft.entries.section(1).ids() %}`

This will create an array of all entries or products that are on the site, given the query parameters you specify. I placed this just above my `{% set navItems = ...` declaration at the top of the template.

Where you are looping through your category groups and categories, you will need to add a query for each iteration of the category loop. **This will add queries to the page** So where I had:

```
{% for cat in attribute(navItems.categories, catGroup.handle) %}
	<li{% if cat.active %} class="active"{% endif %}>
		<a href="{{ url('shop'~cat.url.add) }}" class="add">{{ cat.title}}</a>
		{% if cat.active %} <a href="{{ url('shop'~cat.url.remove) }}" class="remove" title="Remove this filter"><i class="fa fa-minus-circle"></i></a> {% endif %}
	</li>
{% endfor %}
````

I now have this:

```
{% for cat in attribute(navItems.categories, catGroup.handle) %}
	{% set hasActiveProducts = craft.categories.id(cat.attributes.id).relatedTo({ sourceElement: activeProductIds }).groupId([1,2,3]).one() ?? null %}
	{% if hasActiveProducts %}
		<li{% if cat.active %} class="active"{% endif %}>
			<a href="{{ url('shop'~cat.url.add) }}" class="add">{{ cat.title}}</a>
			{% if cat.active %} <a href="{{ url('shop'~cat.url.remove) }}" class="remove" title="Remove this filter"><i class="fa fa-minus-circle"></i></a> {% endif %}
		</li>
	{% endif %}
{% endfor %}
```

This line `{% set hasActiveProducts = craft.categories.id(cat.attributes.id).relatedTo({ sourceElement: activeProductIds }).groupId([1,2,3]).one() ?? null %}` creates a variable that either is null, or not, based off of its query. In this case, I am querying for the category for which iteration of the categories loop I am in (`craft.categories.id(cat.attributes.id)`) and is related to the array of product IDs I setup in step 1 (`.relatedTo({ sourceElement: activeProductIds })`) and then passing an array of groupIds that match the category groups I have showing as filter groups (`.groupId([1,2,3])`) and limiting the query to return `.one()` result since I just care about the current category for the loop iteration I am on.

So, give that a try. Its working here.
